### ISSUE TITLE
Store flagged property in proposals table

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot-sequencer#99]
```[tasklist]
### Tasks
- [ ] SQL to add new coloum to proposals table
- [ ] SQL to add `flagged` property to existing list of proposals on sidekick
- [ ] Update hub to return `flagged` from table instead of moderation data
- [ ] Add new action for space admins to update this property
- [ ] Filter proposals with `flagged` property from hub
```
